# Generated by Django 3.1.3 on 2020-11-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('option', models.IntegerField(choices=[(0, 'JEE'), (1, 'NDA'), (2, 'IAS'), (3, 'SSC CHSL'), (4, 'SBI'), (5, 'CUSTOM')], default=0)),
                ('height', models.IntegerField(default=100)),
                ('width', models.IntegerField(default=100)),
            ],
        ),
    ]
